# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('collage_one', 'Collage One'), ('collage_two', 'Collage Two'), ('collage_three', 'Collage Three'), ('button', 'Button')], help_text='The collage templates have 4 general areas: top-left, top-right, bottom-left and bottom-right. The button template just has one button/link with a description in the middle', max_length=55)),
                ('name', models.CharField(max_length=255)),
                ('top_left_button_one_label', models.CharField(blank=True, help_text='Will display in all the collage templates', max_length=255)),
                ('top_left_button_one_link', models.CharField(blank=True, choices=[('', '--Select--')], max_length=255)),
                ('top_left_background_one_image', models.ImageField(blank=True, null=True, upload_to='template_images')),
                ('top_right_button_one_label', models.CharField(blank=True, help_text='Will display in all the collage templates', max_length=255)),
                ('top_right_button_one_link', models.CharField(blank=True, choices=[('', '--Select--')], max_length=255)),
                ('top_right_background_one_image', models.ImageField(blank=True, null=True, upload_to='template_images')),
                ('top_right_button_two_label', models.CharField(blank=True, help_text='Will display in all the collage templates', max_length=255)),
                ('top_right_button_two_link', models.CharField(blank=True, choices=[('', '--Select--')], max_length=255)),
                ('top_right_background_two_image', models.ImageField(blank=True, null=True, upload_to='template_images')),
                ('top_right_button_three_label', models.CharField(blank=True, help_text='Will only display in the collage one and collage three templates', max_length=255)),
                ('top_right_button_three_link', models.CharField(blank=True, choices=[('', '--Select--')], max_length=255)),
                ('top_right_background_three_image', models.ImageField(blank=True, null=True, upload_to='template_images')),
                ('bottom_left_button_one_label', models.CharField(blank=True, help_text='Will display in all the collage templates', max_length=255)),
                ('bottom_left_button_one_link', models.CharField(blank=True, choices=[('', '--Select--')], max_length=255)),
                ('bottom_left_background_one_image', models.ImageField(blank=True, null=True, upload_to='template_images')),
                ('bottom_left_button_two_label', models.CharField(blank=True, help_text='Will only display in the collage one template', max_length=255)),
                ('bottom_left_button_two_link', models.CharField(blank=True, choices=[('', '--Select--')], max_length=255)),
                ('bottom_left_background_two_image', models.ImageField(blank=True, null=True, upload_to='template_images')),
                ('bottom_right_button_one_label', models.CharField(blank=True, help_text='Will display in all the collage templates', max_length=255)),
                ('bottom_right_button_one_link', models.CharField(blank=True, max_length=255)),
                ('bottom_right_background_one_image', models.ImageField(blank=True, null=True, upload_to='template_images')),
                ('button_label', models.CharField(blank=True, help_text='Will only display in the button template', max_length=255)),
                ('button_description', models.TextField(blank=True)),
                ('button_link', models.CharField(blank=True, choices=[('', '--Select--')], max_length=255)),
                ('button_page_background_image', models.ImageField(blank=True, null=True, upload_to='template_images')),
            ],
        ),
        migrations.AddField(
            model_name='landingpage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Template'),
        ),
    ]
