# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='top_right_sidebar_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='top_right_sidebar_title',
            field=models.TextField(blank=True, help_text='Will only display in the collage templates'),
        ),
        migrations.AlterField(
            model_name='template',
            name='bottom_left_button_one_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='bottom_left_button_two_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_left_button_one_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_right_button_one_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_right_button_three_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_right_button_two_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
