# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 04:12
from __future__ import unicode_literals

from django.db import migrations, models

from nicolock.core.utils import slugify_lower


def create_slugs(apps, schema_editor):
    DesignIdea = apps.get_model('design', 'DesignIdea')
    for idea in DesignIdea.objects.all():
        idea.slug = slugify_lower(idea.name)
        idea.save()

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designidea',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            create_slugs,
            reverse_migration
        ),
    ]
