# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 17:14
from __future__ import unicode_literals

from django.db import migrations


def initialize_menus(apps, schema_editor):
    Menu = apps.get_model('menus', 'Menu')
    Menu.objects.get_or_create(name='Homeowner')
    Menu.objects.get_or_create(name='Contractor')
    Menu.objects.get_or_create(name='Commercial')
    Menu.objects.get_or_create(name='Trade')

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20170417_1948'),
    ]

    operations = [
        migrations.RunPython(initialize_menus, reverse_migration),
    ]
