# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import nicolock.menus.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_initial_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='section',
            field=models.CharField(choices=[('section_one', 'Section One'), ('section_two', 'Section Two'), ('section_three', 'Section Three')], default='section_one', help_text='The section in which this menu will show (for the given url)', max_length=255, validators=[nicolock.menus.validators.validate_slashes], verbose_name='section'),
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default='/page/', help_text='This url will be the page that this menu shows up on.', max_length=255, validators=[nicolock.menus.validators.validate_slashes], verbose_name='url'),
            preserve_default=False,
        ),
    ]
