# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 21:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields
import nicolock.menus.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20170621_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=multiselectfield.db.fields.MultiSelectField(help_text='This url will be the page that this menu shows up on.', max_length=255, validators=[nicolock.menus.validators.validate_slashes], verbose_name='url'),
        ),
    ]
