# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models

from nicolock.core.utils import slugify_lower


def create_slugs(apps, schema_editor):
    Gallery = apps.get_model('galleries', 'Gallery')
    for gallery in Gallery.objects.all():
        gallery.slug = slugify_lower(gallery.name)
        gallery.save()

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_inspirationalphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            create_slugs,
            reverse_migration
        ),
    ]
