# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='company_profile',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
