# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_auto_20170424_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='patterns_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='products_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
