# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_auto_20170425_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['name'], 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterModelOptions(
            name='inspirationalphoto',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
