# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0009_gallery_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='galleries.Project'),
        ),
    ]
