# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 22:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0010_auto_20170427_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspirationalphoto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
