# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Will fall back to the last time saved', verbose_name='order')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
                'ordering': ['order', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='Question')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('order', models.PositiveIntegerField(default=1, help_text='Will fall back to the last time saved', verbose_name='Order')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faqs.Category')),
                ('related', models.ManyToManyField(blank=True, related_name='_faq_related_+', to='faqs.Faq')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
