# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 19:51
from __future__ import unicode_literals

from django.db import migrations

def initialize_auth_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    dev_group = Group.objects.get_or_create(name='Developer')
    nicolock_group = Group.objects.get_or_create(name='Nicolock Admin')
    editor_group = Group.objects.get_or_create(name='Editor')

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_auth_groups, reverse_migration),
    ]
