# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 22:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initialize_auth_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='company name')),
                ('address', models.TextField(blank=True, verbose_name='company address')),
                ('website', models.URLField(blank=True, verbose_name='company website')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. \nUp to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='company phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='company email')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='contact name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. \nUp to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='contact phone number')),
                ('area_covered', models.CharField(blank=True, max_length=255, verbose_name='area_covered')),
                ('specialtys', models.CharField(blank=True, max_length=255, verbose_name='specialtys')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
