# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161207_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='specialtys',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='specialties',
            field=models.CharField(blank=True, max_length=255, verbose_name='specialties'),
        ),
    ]
