# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.utils import IntegrityError

from nicolock.core.utils import slugify_lower


def create_slugs(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.slug = slugify_lower(user.email)
        user.save()

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161215_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            create_slugs,
            reverse_migration
        ),
    ]
