# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_companyprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
