# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170314_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractors', models.ManyToManyField(related_name='contractor_lists', to=settings.AUTH_USER_MODEL)),
                ('homeowner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
