# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_contractorlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_images', verbose_name='image'),
        ),
    ]
