# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_companyprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address_line_one',
            field=models.TextField(blank=True, null=True, verbose_name='address line one'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address_line_two',
            field=models.TextField(blank=True, null=True, verbose_name='address line two'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='state',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='state'),
        ),
    ]
