# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170503_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorlist',
            name='contractors',
            field=models.ManyToManyField(blank=True, related_name='contractor_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
