# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 15:35
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170627_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='company name')),
                ('address_line_one', models.TextField(blank=True, null=True, verbose_name='address line one')),
                ('address_line_two', models.TextField(blank=True, null=True, verbose_name='address line two')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=55, null=True, verbose_name='state')),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='postal code')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('website', models.URLField(blank=True, verbose_name='company website')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='company phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='company email')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='contact name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=16, verbose_name='contact phone number')),
                ('area_covered', models.CharField(blank=True, max_length=255, verbose_name='area_covered')),
                ('specialties', models.CharField(blank=True, max_length=255, verbose_name='specialties')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_profile_images', verbose_name='image')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user__name', unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'contractors',
                'verbose_name': 'contractor',
            },
        ),
    ]
