# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 20:38
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20170627_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='certifications',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('np', 'NP'), ('nw', 'NW')], max_length=55, verbose_name='certifications'),
        ),
    ]
