# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='address')),
                ('datetime', models.DateTimeField()),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('state', models.CharField(max_length=55, verbose_name='state')),
                ('postal_code', models.CharField(max_length=12, verbose_name='postal code')),
            ],
        ),
    ]
