# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170817_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='register_link',
            field=models.URLField(blank=True, verbose_name='register_link'),
        ),
    ]
