# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 18:46
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170817_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
