# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('url', models.URLField(help_text="Please get the share url from the share link below the video. The url should look something like this: 'https://youtu.be/AslncyG8whg'", verbose_name='url')),
                ('tags', models.ManyToManyField(to='videos.Tag')),
            ],
        ),
    ]
