# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models

from nicolock.core.utils import slugify_lower


def create_slugs(apps, schema_editor):
    Video = apps.get_model('videos', 'Video')
    for video in Video.objects.all():
        video.slug = slugify_lower(video.name)
        video.save()

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            create_slugs,
            reverse_migration
        ),
    ]
