# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='like count'),
        ),
    ]
