# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['name']},
        ),
    ]
