# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20170316_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='lon',
            new_name='lng',
        ),
    ]
