# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_auto_20170317_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
