# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 15:31
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.ImageField(upload_to='innovation_images', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
