# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 00:29
from __future__ import unicode_literals

from django.db import migrations

def initialize_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.get_or_create(name='Pavers')
    Category.objects.get_or_create(name='Wall Systems')
    Category.objects.get_or_create(name='Outdoor Living')
    Category.objects.get_or_create(name='Accents')
    Category.objects.get_or_create(name='Nicostone')

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_categories, reverse_migration),
    ]
