# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initialize_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['order', 'modified'], 'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['order', 'modified'], 'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order', 'modified'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={'ordering': ['order', 'modified'], 'verbose_name': 'pattern', 'verbose_name_plural': 'patterns'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'modified'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='spec',
            options={'ordering': ['order', 'modified'], 'verbose_name': 'spec', 'verbose_name_plural': 'specs'},
        ),
    ]
