# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161207_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_type',
            field=models.CharField(blank=True, choices=[('premium', 'Premium'), ('deluxe', 'Deluxe')], max_length=10, verbose_name='color type'),
        ),
    ]
