# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models

from nicolock.core.utils import slugify_lower


def create_slugs(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    for category in Category.objects.all():
        category.slug = slugify_lower(category.name)
        category.save()

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_color_color_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            create_slugs,
            reverse_migration
        ),
    ]
