# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 00:09
from __future__ import unicode_literals

from django.db import migrations, models

from nicolock.core.utils import slugify_lower


def create_slugs(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        product.slug = slugify_lower(product.name)
        product.save()

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            create_slugs,
            reverse_migration
        ),
    ]
