# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 00:28
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20161221_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='product_specs'),
        ),
    ]
