# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 19:04
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170503_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uses',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('patio', 'Patio'), ('walkway', 'Walkway'), ('driveway', 'Driveway'), ('pool', 'Pool')], max_length=255, verbose_name='uses'),
        ),
    ]
