# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170526_1624'),
        ('products', '0011_auto_20170524_1904'),
    ]

    operations = [
    ]
