# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_merge_20170526_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec_chart',
            field=models.ImageField(blank=True, null=True, upload_to='spec_charts', verbose_name='spec chart'),
        ),
    ]
