# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170626_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='file',
        ),
    ]
