# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_spec_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
