# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 21:21
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_countertop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_description',
            field=froala_editor.fields.FroalaField(blank=True, verbose_name='extra description'),
        ),
    ]
