# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-11 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_create_color_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.Product'),
        ),
    ]
