# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-11 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20180111_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'color categories'},
        ),
        migrations.AddField(
            model_name='colorcategory',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Will fall back to the last time saved', verbose_name='order'),
        ),
    ]
