# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='phone'),
        ),
    ]
