# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreps', '0003_auto_20170317_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=12, verbose_name='postal code')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
            ],
        ),
        migrations.RemoveField(
            model_name='salesrep',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='salesrep',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='salesrep',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='salesrep',
            name='postal_codes',
            field=models.ManyToManyField(related_name='sales_reps', to='salesreps.PostalCode'),
        ),
    ]
