# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreps', '0004_auto_20170321_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='original',
            field=models.ImageField(upload_to='salesreps_images', verbose_name='image'),
        ),
    ]
