# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 20:10
from __future__ import unicode_literals

import os

from django.core.management import call_command
from django.db import migrations


def import_postal_codes_fixture(apps, schema_editor):
    if os.environ.get('LK_ENV') != 'production':
        return
    call_command('loaddata', 'zipcodes2.json')

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('salesreps', '0006_initial_postal_codes_fixture1'),
    ]

    operations = [
        migrations.RunPython(import_postal_codes_fixture, reverse_migration),
    ]
