# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 16:41
from __future__ import unicode_literals

import os, time

from django.db import migrations

from nicolock.salesreps.models import postal_code_created


def initialize_postal_codes(apps, schema_editor):
    if os.environ.get('LK_ENV') != 'production':
        return
    PostalCode = apps.get_model('salesreps', 'PostalCode')
    module_dir = os.path.dirname(__file__)
    file_path = os.path.join(module_dir, 'data/nicozips.txt')
    with open(file_path) as f:
        for postal_code_text in f:
            try:
                PostalCode.objects.get(postal_code=postal_code_text.strip())
            except PostalCode.DoesNotExist:
                new_postal_code = PostalCode.objects.create(
                    postal_code=postal_code_text.strip())
                postal_code_created(PostalCode, new_postal_code, True)
                time.sleep(0.75)

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('salesreps', '0015_initial_postal_codes_fixture10'),
    ]

    operations = [
        migrations.RunPython(initialize_postal_codes, reverse_migration),
    ]
